### ISSUE TITLE
doesn't work with locally installed dependencies?

### ISSUE THREAD

**Issue by ianstormtaylor** [gibatronic/make-help#5]
When I try to use it as a locally installed dependency, I get:

```
./node_modules/.bin/make-help: line 45: cd: ../make-help/bin: No such file or directory
./node_modules/.bin/make-help: line 45: cd: /Users/Storm/dev/contentshq/api/../lib: No such file or directory
awk: can't open file /Users/Storm/dev/contentshq/api/commented-targets.awk
 source line number 1 source file /Users/Storm/dev/contentshq/api/commented-targets.awk
 context is
     >>>  <<< 
```

Would love to use this, but I'd like to install it locally so that it doesn't add a hidden global dependency to the current project.

**Comment by gibatronic** [comment]
sure, in my projects I also use it locally.
but I don't understand how you got that error.

please, take a look in this project where I use it: [github.com/rbsdev/scaffolding-front-end](https://github.com/rbsdev/scaffolding-front-end).
there `make-help` is declared as a regular dependency in [`devDependencies`](https://github.com/rbsdev/scaffolding-front-end/blob/master/package.json).
and in the [`tasks/help`](https://github.com/rbsdev/scaffolding-front-end/blob/master/tasks/help) file you can see `make-help` being called.

let me know if you run into any problem!

**Comment by gibatronic** [comment]
I saw what the problem was and fixed it, thanks for reporting it!
the script was getting lost while trying to resolve relative paths into absolute ones.
