### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rheaton** [gibatronic/make-help#6]
Hello,

There is no license for this project, would you consider adding one? 

https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

Thank you!

**Comment by gibatronic** [comment]
Oh, indeed… on the [package manifest](https://github.com/gibatronic/make-help/blob/a673141d5b5b2edb478cc14640913f046b6d853d/package.json#L22) I stated the MIT license, but somehow forgot about the root file manifest.
